# Generated by Django 3.0.4 on 2020-06-09 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='award',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pay',
            name='payment_summ',
            field=models.FloatField(max_length=12, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
