# Generated by Django 3.0.4 on 2020-06-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200609_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redemption',
            name='payment_summ',
            field=models.FloatField(blank=True, max_length=16),
        ),
    ]
