# Generated by Django 3.0.4 on 2020-06-10 09:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200609_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_summ', models.FloatField(blank=True, max_length=16)),
                ('create_data', models.DateTimeField(auto_now_add=True)),
                ('processing_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('account_number', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'verbose_name': 'Repayment',
                'verbose_name_plural': 'Repayments',
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.DeleteModel(
            name='Redemption',
        ),
        migrations.AddField(
            model_name='repayment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Customer'),
        ),
    ]
