# Generated by Django 3.0.4 on 2020-04-01 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=16)),
                ('fuel_util', models.FloatField(max_length=3)),
                ('date_assembly', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=2)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='carcompany_app.User')),
                ('specialization', models.CharField(choices=[('Truck', 'Truck driver'), ('Car', 'Passenger car')], default='Car', max_length=5)),
            ],
            bases=('carcompany_app.user',),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='carcompany_app.User')),
                ('department', models.CharField(choices=[('F', 'Finance department'), ('T', 'Technical department'), ('A', 'Administrate department')], default='A', max_length=1)),
            ],
            bases=('carcompany_app.user',),
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=64)),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carcompany_app.Car')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carcompany_app.User')),
            ],
        ),
    ]
