# Generated by Django 3.0.4 on 2020-04-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carcompany_app', '0004_auto_20200401_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='status_for_car',
            field=models.CharField(choices=[('ACT', 'Active'), ('NO_ACT', 'No active')], default='NO_ACT', max_length=6),
        ),
    ]
