# Generated by Django 3.0.4 on 2020-04-10 09:55

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=16)),
                ('fuel_util', models.FloatField(max_length=3)),
                ('date_assembly', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('department', models.CharField(choices=[('F', 'Finance department'), ('T', 'Technical department'), ('A', 'Administrate department')], default='A', max_length=1)),
                ('of_enterprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carcompany_app.Enterprise')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('specialization', models.CharField(choices=[('Truck', 'Truck driver'), ('Car', 'Passenger car')], default='Car', max_length=5)),
                ('status_for_car', models.CharField(choices=[('ACT', 'Active'), ('NO_ACT', 'No active')], default='NO_ACT', max_length=6)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carcompany_app.Car')),
                ('of_enterprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carcompany_app.Enterprise')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='of_enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carcompany_app.Enterprise'),
        ),
    ]
