# Generated by Django 3.0.4 on 2020-05-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carcompany_app', '0003_enterprise_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='date_assembly',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
