# Generated by Django 3.0.4 on 2020-06-02 12:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carcompany_app', '0005_auto_20200526_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='date_of_buy',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coords', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='longitude/latitude')),
                ('begin_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('to_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carcompany_app.Car')),
            ],
        ),
    ]
