# Generated by Django 3.0.4 on 2020-06-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carcompany_app', '0006_auto_20200602_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='coords',
        ),
        migrations.AddField(
            model_name='trip',
            name='geo_data',
            field=models.FileField(blank=True, null=True, upload_to='geo_tracks/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='trip',
            name='save_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
