# Generated by Django 3.0.4 on 2020-06-04 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carcompany_app', '0008_remove_trip_geo_data'),
        ('carcompany_app', '0006_auto_20200604_1625'),
    ]

    operations = [
    ]
