# Generated by Django 3.0.4 on 2020-05-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carcompany_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_util',
            field=models.CharField(max_length=5),
        ),
    ]
