# Generated by Django 3.0.4 on 2020-06-05 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carcompany_app', '0002_auto_20200604_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_data', models.FileField(blank=True, null=True, upload_to='geo_tracks/%Y/%m/%d')),
                ('begin_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('save_time', models.DateTimeField(auto_now=True)),
                ('to_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carcompany_app.Car')),
            ],
        ),
        migrations.DeleteModel(
            name='Trips',
        ),
    ]
